spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_car_rent?createDatabaseIfNotExist=true
    username: root
    password: password
    drive-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl